#!/bin/sh

#################################
# Frontend apache server commands
#################################

DIR=/var/www

start() {
	sudo service apache2 start
}

stop() {
	sudo service apache2 stop
}

restart() {
	sudo service apache2 restart
}

copy() {
	stop
	sudo rm -rf $DIR/html
	sudo mkdir $DIR/html
	sudo cp -av $HOME/bus-tracker-frontend/site/* /var/www/html
	minify
	start
}

minify() {
	# Minifies JS files in bus-tracker/
	for file in $DIR/html/js/bus-tracker/* ; do
		sudo uglifyjs $file -cmo $file
	done
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	copy)
		copy
		;;
	minify)
		minify
		;;
	*)
	echo "Usage: $0 {start|stop|restart|copy}"
esac
