#!/bin/sh

#################################
# Frontend apache server commands
#################################

start() {
	sudo service apache2 start
}

stop() {
	sudo service apache2 stop
}

restart() {
	sudo service apache2 restart
}

copy() {
	stop
	sudo cp -av $HOME/bus-tracker-frontend/site/* /var/www/html
	minify
	start
}

minify() {
	DIR=/var/www/html/js
	
	# Minifies require.js
	sudo uglifyjs $DIR/bower_components/requirejs/require.js -cmo require.js
	
	# Minifies JS files in bus-tracker/
	for file in $DIR/bus-tracker/* ; do
		sudo uglifyjs $file -cmo $file
	done
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	copy)
		copy
		;;
	*)
	echo "Usage: $0 {start|stop|restart|copy}"
esac
